import type { Product, Category, Testimonial, NavLink, GALLERY } from "./types";

/* =====================================================
   NAV LINKS
===================================================== */

export const NAV_LINKS: NavLink[] = [
  { name: "Home", path: "/" },
  { name: "Bronze Statues", path: "/products?category=Bronze Statues" },
  { name: "Home Decor Bronze", path: "/products?category=Home decor bronze" },
  { name: "Furniture", path: "/products?category=Furniture" },
  { name: "Puja Items", path: "/products?category=Puja Items" },
  { name: "About Us", path: "/about" },
  { name: "Contact", path: "/contact" },
];

/* =====================================================
   BRONZE STATUE PRODUCTS (ID: 1–62)
===================================================== */

export const STATUE_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Statue Item 10004",
    imageUrl: "/assets/categories/statues/10004.jpg",
    category: "Bronze Statues",
    description: "Handcrafted traditional bronze statue with fine detailing.",
  },
  {
    id: 2,
    name: "Statue Item 10030",
    imageUrl: "/assets/categories/statues/10030.jpg",
    category: "Home decor bronze",
    description: "Classic handcrafted bronze statue suitable for home decor.",
  },
  {
    id: 3,
    name: "Statue Item 10031",
    imageUrl: "/assets/categories/statues/10031.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with artistic finish.",
  },
  {
    id: 4,
    name: "Statue Item 10032",
    imageUrl: "/assets/categories/statues/10032.jpg",
    category: "Home decor bronze",
    description: "Elegant statue crafted using traditional methods.",
  },
  {
    id: 5,
    name: "Statue Item 10033",
    imageUrl: "/assets/categories/statues/10033.jpg",
    category: "Home decor bronze",
    description: "Temple-style handcrafted bronze statue.",
  },
  {
    id: 6,
    name: "Statue Item 10034",
    imageUrl: "/assets/categories/statues/10034.jpg",
    category: "Bronze Statues",
    description: "Premium quality decorative bronze statue.",
  },
  {
    id: 7,
    name: "Statue Item 10036",
    imageUrl: "/assets/categories/statues/10036.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue.",
  },
  {
    id: 8,
    name: "Statue Item 10037",
    imageUrl: "/assets/categories/statues/10037.jpg",
    category: "Bronze Statues",
    description: "Artisan-made bronze statue with classic design.",
  },
  {
    id: 9,
    name: "Statue Item 10038",
    imageUrl: "/assets/categories/statues/10038.jpg",
    category: "Bronze Statues",
    description: "Traditional religious bronze statue.",
  },
  {
    id: 10,
    name: "Statue Item 10042",
    imageUrl: "/assets/categories/statues/10042.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with antique finish.",
  },

  {
    id: 11,
    name: "Statue Item 10044",
    imageUrl: "/assets/categories/statues/10044.jpg",
    category: "Bronze Statues",
    description: "Classic temple-style bronze statue.",
  },
  {
    id: 12,
    name: "Statue Item 10045",
    imageUrl: "/assets/categories/statues/10045.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue décor.",
  },
  {
    id: 13,
    name: "Statue Item 10046",
    imageUrl: "/assets/categories/statues/10046.jpg",
    category: "Bronze Statues",
    description: "Premium bronze statue with intricate carvings.",
  },
  {
    id: 14,
    name: "Statue Item 10047",
    imageUrl: "/assets/categories/statues/10047.jpg",
    category: "Bronze Statues",
    description: "Elegant handcrafted religious bronze statue.",
  },
  {
    id: 15,
    name: "Statue Item 10048",
    imageUrl: "/assets/categories/statues/10048.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with fine metalwork.",
  },
  {
    id: 16,
    name: "Statue Item 10049",
    imageUrl: "/assets/categories/statues/10049.jpg",
    category: "Bronze Statues",
    description: "Classic bronze statue for spiritual decor.",
  },
  {
    id: 17,
    name: "Statue Item 10050",
    imageUrl: "/assets/categories/statues/10050.jpg",
    category: "Home decor bronze",
    description: "Handcrafted bronze statue with traditional symbolism.",
  },
  {
    id: 20,
    name: "Statue Item 10067",
    imageUrl: "/assets/categories/statues/10067.jpg",
    category: "Home decor bronze",
    description: "Handcrafted bronze statue with detailed artistry.",
  },

  {
    id: 21,
    name: "Statue Item 10068",
    imageUrl: "/assets/categories/statues/10068.jpg",
    category: "Bronze Statues",
    description: "Classic religious bronze statue.",
  },
  {
    id: 23,
    name: "Statue Item 10070",
    imageUrl: "/assets/categories/statues/10070.jpg",
    category: "Bronze Statues",
    description: "Temple-style handcrafted bronze statue.",
  },
  {
    id: 24,
    name: "Statue Item 10071",
    imageUrl: "/assets/categories/statues/10071.jpg",
    category: "Bronze Statues",
    description: "Premium handcrafted bronze statue.",
  },
  {
    id: 25,
    name: "Statue Item 10072",
    imageUrl: "/assets/categories/statues/10072.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with fine detailing.",
  },
  {
    id: 26,
    name: "Statue Item 10073",
    imageUrl: "/assets/categories/statues/10073.jpg",
    category: "Bronze Statues",
    description: "Handcrafted religious bronze statue.",
  },
  {
    id: 27,
    name: "Statue Item 10076",
    imageUrl: "/assets/categories/statues/10076.jpg",
    category: "Bronze Statues",
    description: "Classic handcrafted bronze statue.",
  },
  {
    id: 28,
    name: "Statue Item 10079",
    imageUrl: "/assets/categories/statues/10079.jpg",
    category: "Home decor bronze",
    description: "Traditional decorative bronze statue.",
  },
  {
    id: 30,
    name: "Statue Item 10081",
    imageUrl: "/assets/categories/statues/10081.jpg",
    category: "Home decor bronze",
    description: "Handcrafted bronze statue with classic design.",
  },

  {
    id: 31,
    name: "Statue Item 10082",
    imageUrl: "/assets/categories/statues/10082.jpg",
    category: "Bronze Statues",
    description: "Elegant bronze statue with fine finish.",
  },
  {
    id: 32,
    name: "Statue Item 10083",
    imageUrl: "/assets/categories/statues/10083.jpg",
    category: "Bronze Statues",
    description: "Traditional religious bronze statue.",
  },
  {
    id: 33,
    name: "Statue Item 10088",
    imageUrl: "/assets/categories/statues/10088.jpg",
    category: "Home decor bronze",
    description: "Handcrafted bronze statue for decor.",
  },
  {
    id: 34,
    name: "Statue Item 10090",
    imageUrl: "/assets/categories/statues/10090.jpg",
    category: "Bronze Statues",
    description: "Classic temple-style bronze statue.",
  },
  {
    id: 35,
    name: "Statue Item 10096",
    imageUrl: "/assets/categories/statues/10096.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue décor.",
  },
  {
    id: 36,
    name: "Statue Item 10097",
    imageUrl: "/assets/categories/statues/10097.jpg",
    category: "Bronze Statues",
    description: "Premium bronze statue with artistic finish.",
  },

  {
    id: 37,
    name: "Statue Item 10098",
    imageUrl: "/assets/categories/statues/10098.jpg",
    category: "Bronze Statues",
    description: "Classic handcrafted bronze statue.",
  },
  {
    id: 38,
    name: "Statue Item 10104",
    imageUrl: "/assets/categories/statues/10104.jpg",
    category: "Bronze Statues",
    description: "Traditional religious bronze statue.",
  },
  {
    id: 39,
    name: "Statue Item 10106",
    imageUrl: "/assets/categories/statues/10106.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with intricate carvings.",
  },
  {
    id: 40,
    name: "Statue Item 10107",
    imageUrl: "/assets/categories/statues/10107.jpg",
    category: "Bronze Statues",
    description: "Decorative bronze statue with classic style.",
  },
  {
    id: 41,
    name: "Statue Item 10108",
    imageUrl: "/assets/categories/statues/10108.jpg",
    category: "Bronze Statues",
    description: "Temple-style handcrafted bronze statue.",
  },
  {
    id: 42,
    name: "Statue Item 10111",
    imageUrl: "/assets/categories/statues/10111.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue for worship.",
  },
  {
    id: 43,
    name: "Statue Item 10112",
    imageUrl: "/assets/categories/statues/10112.jpg",
    category: "Bronze Statues",
    description: "Premium handcrafted religious bronze statue.",
  },
  {
    id: 44,
    name: "Statue Item 10114",
    imageUrl: "/assets/categories/statues/10114.jpg",
    category: "Bronze Statues",
    description: "Classic bronze statue for decor.",
  },
  {
    id: 45,
    name: "Statue Item 10115",
    imageUrl: "/assets/categories/statues/10115.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue.",
  },
  {
    id: 46,
    name: "Statue Item 10117",
    imageUrl: "/assets/categories/statues/10117.jpg",
    category: "Bronze Statues",
    description: "Temple-style bronze statue.",
  },
  {
    id: 47,
    name: "Statue Item 10121",
    imageUrl: "/assets/categories/statues/10121.jpg",
    category: "Bronze Statues",
    description: "Classic religious bronze statue.",
  },
  {
    id: 48,
    name: "Statue Item 10122",
    imageUrl: "/assets/categories/statues/10122.jpg",
    category: "Bronze Statues",
    description: "Decorative bronze statue.",
  },
  {
    id: 49,
    name: "Statue Item 10123",
    imageUrl: "/assets/categories/statues/10123.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue.",
  },
  {
    id: 50,
    name: "Statue Item 10124",
    imageUrl: "/assets/categories/statues/10124.jpg",
    category: "Bronze Statues",
    description: "Elegant bronze statue for spiritual decor.",
  },
  {
    id: 51,
    name: "Statue Item 10126",
    imageUrl: "/assets/categories/statues/10126.jpg",
    category: "Bronze Statues",
    description: "Classic temple-style bronze statue.",
  },
  {
    id: 52,
    name: "Statue Item 10127",
    imageUrl: "/assets/categories/statues/10127.jpg",
    category: "Bronze Statues",
    description: "Premium handcrafted bronze statue.",
  },
  {
    id: 53,
    name: "Statue Item 10128",
    imageUrl: "/assets/categories/statues/10128.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with fine finish.",
  },
  {
    id: 54,
    name: "Statue Item 10129",
    imageUrl: "/assets/categories/statues/10129.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue for temple decor.",
  },
  {
    id: 55,
    name: "Statue Item 10130",
    imageUrl: "/assets/categories/statues/10130.jpg",
    category: "Bronze Statues",
    description: "Classic religious bronze statue.",
  },
  {
    id: 56,
    name: "Statue Item 10131",
    imageUrl: "/assets/categories/statues/10131.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue.",
  },
  {
    id: 57,
    name: "Statue Item 10132",
    imageUrl: "/assets/categories/statues/10132.jpg",
    category: "Bronze Statues",
    description: "Decorative bronze statue.",
  },
  {
    id: 58,
    name: "Statue Item 10133",
    imageUrl: "/assets/categories/statues/10133.jpg",
    category: "Bronze Statues",
    description: "Temple-style handcrafted bronze statue.",
  },
  {
    id: 59,
    name: "Statue Item 10134",
    imageUrl: "/assets/categories/statues/10134.jpg",
    category: "Bronze Statues",
    description: "Premium bronze statue with artistic design.",
  },
  {
    id: 60,
    name: "Statue Item 10135",
    imageUrl: "/assets/categories/statues/10135.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue décor.",
  },
  {
    id: 61,
    name: "Statue Item 10141",
    imageUrl: "/assets/categories/statues/10141.jpg",
    category: "Bronze Statues",
    description: "Classic bronze statue for temples.",
  },
  {
    id: 62,
    name: "Statue Item 10146",
    imageUrl: "/assets/categories/statues/10146.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with fine craftsmanship.",
  },
  {
    id: 63,
    name: "Statue Item 10147",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0003.jpg",
    category: "Bronze Statues",
    description: "Handcrafted traditional bronze statue with fine detailing.",
  },
  {
    id: 64,
    name: "Statue Item 10148",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0004.jpg",
    category: "Bronze Statues",
    description: "Classic handcrafted bronze statue suitable for home decor.",
  },
  {
    id: 65,
    name: "Statue Item 10149",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0005.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with artistic finish.",
  },
  {
    id: 66,
    name: "Statue Item 10150",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0006.jpg",
    category: "Bronze Statues",
    description: "Elegant statue crafted using traditional methods.",
  },
  {
    id: 67,
    name: "Statue Item 10151",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0007.jpg",
    category: "Bronze Statues",
    description: "Temple-style handcrafted bronze statue.",
  },
  {
    id: 68,
    name: "Statue Item 10152",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0008.jpg",
    category: "Bronze Statues",
    description: "Premium quality decorative bronze statue.",
  },
  {
    id: 69,
    name: "Statue Item 10153",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0009.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue.",
  },
  {
    id: 70,
    name: "Statue Item 10154",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0010.jpg",
    category: "Bronze Statues",
    description: "Artisan-made bronze statue with classic design.",
  },
  {
    id: 71,
    name: "Statue Item 10155",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0011.jpg",
    category: "Bronze Statues",
    description: "Traditional religious bronze statue.",
  },
  {
    id: 72,
    name: "Statue Item 10156",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0012.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with antique finish.",
  },
  {
    id: 73,
    name: "Statue Item 10157",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0013.jpg",
    category: "Bronze Statues",
    description: "Classic temple-style bronze statue.",
  },
  {
    id: 74,
    name: "Statue Item 10158",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0014.jpg",
    category: "Bronze Statues",
    description: "Traditional handcrafted bronze statue décor.",
  },
  {
    id: 75,
    name: "Statue Item 10159",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0015.jpg",
    category: "Bronze Statues",
    description: "Premium bronze statue with intricate carvings.",
  },
  {
    id: 76,
    name: "Statue Item 10160",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0016.jpg",
    category: "Bronze Statues",
    description: "Elegant handcrafted religious bronze statue.",
  },
  {
    id: 77,
    name: "Statue Item 10161",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0017.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with fine metalwork.",
  },
  {
    id: 78,
    name: "Statue Item 10162",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0018.jpg",
    category: "Bronze Statues",
    description: "Classic bronze statue for spiritual decor.",
  },
  {
    id: 79,
    name: "Statue Item 10163",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0019.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with traditional symbolism.",
  },
  {
    id: 80,
    name: "Statue Item 10164",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0020.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with detailed artistry.",
  },
  {
    id: 81,
    name: "Statue Item 10165",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0021.jpg",
    category: "Bronze Statues",
    description: "Classic religious bronze statue.",
  },
  {
    id: 82,
    name: "Statue Item 10166",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0022.jpg",
    category: "Bronze Statues",
    description: "Temple-style handcrafted bronze statue.",
  },
  {
    id: 83,
    name: "Statue Item 10167",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0023.jpg",
    category: "Bronze Statues",
    description: "Premium handcrafted bronze statue.",
  },
  {
    id: 84,
    name: "Statue Item 10168",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0024.jpg",
    category: "Bronze Statues",
    description: "Traditional bronze statue with fine detailing.",
  },
  {
    id: 85,
    name: "Statue Item 10169",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0025.jpg",
    category: "Bronze Statues",
    description: "Handcrafted religious bronze statue.",
  },
  {
    id: 86,
    name: "Statue Item 10170",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0026.jpg",
    category: "Bronze Statues",
    description: "Classic handcrafted bronze statue.",
  },
  {
    id: 87,
    name: "Statue Item 10171",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0027.jpg",
    category: "Bronze Statues",
    description: "Traditional decorative bronze statue.",
  },
  {
    id: 88,
    name: "Statue Item 10172",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0028.jpg",
    category: "Bronze Statues",
    description: "Handcrafted bronze statue with classic design.",
  },
  {
    id: 89,
    name: "Statue Item 10173",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0029.jpg",
    category: "Bronze Statues",
    description: "Elegant bronze statue with fine finish.",
  },
  {
    id: 90,
    name: "Statue Item 10174",
    imageUrl: "/assets/bronces/Scanned_20260615-1149_page-0030.jpg",
    category: "Bronze Statues",
    description: "Traditional religious bronze statue.",
  },
  {
    id: 91,
    name: "Statue Item 2966",
    imageUrl: "/assets/categories/home_decor/IMG_2966.JPG",
    category: "Home decor bronze",
    description: "Elegant handcrafted bronze home decor item.",
  },
  {
    id: 92,
    name: "Statue Item 2968",
    imageUrl: "/assets/categories/home_decor/IMG_2968.JPG",
    category: "Home decor bronze",
    description: "Traditional handcrafted bronze home decor item.",
  },
  {
    id: 93,
    name: "Statue Item 2969",
    imageUrl: "/assets/categories/home_decor/IMG_2969.JPG",
    category: "Home decor bronze",
    description: "Classic handcrafted bronze home decor item.",
  },
  {
    id: 94,
    name: "Statue Item 2970",
    imageUrl: "/assets/categories/home_decor/IMG_2970.JPG",
    category: "Home decor bronze",
    description: "Artisan-made handcrafted bronze home decor item.",
  },
  {
    id: 95,
    name: "Statue Item 2971",
    imageUrl: "/assets/categories/home_decor/IMG_2971.JPG",
    category: "Home decor bronze",
    description: "Premium handcrafted bronze home decor item.",
  },
  {
    id: 96,
    name: "Statue Item 2972",
    imageUrl: "/assets/categories/home_decor/IMG_2972.JPG",
    category: "Home decor bronze",
    description: "Beautiful handcrafted bronze home decor item.",
  },
  {
    id: 97,
    name: "Statue Item 2973",
    imageUrl: "/assets/categories/home_decor/IMG_2973.JPG",
    category: "Home decor bronze",
    description: "Handcrafted traditional bronze home decor item.",
  },
  {
    id: 98,
    name: "Statue Item 2974",
    imageUrl: "/assets/categories/home_decor/IMG_2974.JPG",
    category: "Home decor bronze",
    description: "Exquisite handcrafted bronze home decor item.",
  },
  {
    id: 99,
    name: "Statue Item 2975",
    imageUrl: "/assets/categories/home_decor/IMG_2975.JPG",
    category: "Home decor bronze",
    description: "Fine handcrafted bronze home decor item.",
  },
];

/* =====================================================
   FURNITURE PRODUCTS (ID: 101–131)
===================================================== */

export const FURNITURE_PRODUCTS: Product[] = [
  {
    id: 101,
    name: "Furniture Item 10007",
    imageUrl: "/assets/categories/furniture/10007.jpg",
    category: "Furniture",
    description: "Handcrafted wooden furniture with traditional design.",
  },
  {
    id: 102,
    name: "Furniture Item 10008",
    imageUrl: "/assets/categories/furniture/10008.jpg",
    category: "Furniture",
    description: "Premium quality furniture suitable for home interiors.",
  },
  {
    id: 106,
    name: "Furniture Item 10014",
    imageUrl: "/assets/categories/furniture/10014.jpg",
    category: "Furniture",
    description: "Well-crafted furniture item ideal for living spaces.",
  },
  {
    id: 107,
    name: "Furniture Item 10015",
    imageUrl: "/assets/categories/furniture/10015.jpg",
    category: "Furniture",
    description: "Modern-style furniture with functional design.",
  },
  {
    id: 108,
    name: "Furniture Item 10016",
    imageUrl: "/assets/categories/furniture/10016.jpg",
    category: "Furniture",
    description: "Strong wooden furniture for everyday use.",
  },
  {
    id: 109,
    name: "Furniture Item 10017",
    imageUrl: "/assets/categories/furniture/10017.jpg",
    category: "Furniture",
    description: "Elegant furniture piece with premium finish.",
  },
  {
    id: 110,
    name: "Furniture Item 10018",
    imageUrl: "/assets/categories/furniture/10018.jpg",
    category: "Furniture",
    description: "Compact furniture suitable for small spaces.",
  },
  {
    id: 111,
    name: "Furniture Item 10019",
    imageUrl: "/assets/categories/furniture/10019.jpg",
    category: "Furniture",
    description: "Traditional wooden furniture décor.",
  },
  {
    id: 114,
    name: "Furniture Item 10022",
    imageUrl: "/assets/categories/furniture/10022.jpg",
    category: "Furniture",
    description: "Traditional furniture suitable for homes and offices.",
  },
  {
    id: 115,
    name: "Furniture Item 10023",
    imageUrl: "/assets/categories/furniture/10023.jpg",
    category: "Furniture",
    description: "Well-polished wooden furniture piece.",
  },
  {
    id: 116,
    name: "Furniture Item 10024",
    imageUrl: "/assets/categories/furniture/10024.jpg",
    category: "Furniture",
    description: "Classic furniture item with solid build.",
  },
  {
    id: 117,
    name: "Furniture Item 10025",
    imageUrl: "/assets/categories/furniture/10025.jpg",
    category: "Furniture",
    description: "Multipurpose wooden furniture.",
  },
  {
    id: 118,
    name: "Furniture Item 10026",
    imageUrl: "/assets/categories/furniture/10026.jpg",
    category: "Furniture",
    description: "Premium furniture with modern aesthetics.",
  },
  {
    id: 119,
    name: "Furniture Item 10027",
    imageUrl: "/assets/categories/furniture/10027.jpg",
    category: "Furniture",
    description: "Durable furniture ideal for long-term use.",
  },
  {
    id: 120,
    name: "Furniture Item 10028",
    imageUrl: "/assets/categories/furniture/10028.jpg",
    category: "Furniture",
    description: "Elegant wooden furniture with smooth finish.",
  },
  {
    id: 121,
    name: "Furniture Item 10029",
    imageUrl: "/assets/categories/furniture/10029.jpg",
    category: "Furniture",
    description: "Traditional furniture with fine craftsmanship.",
  },
  {
    id: 123,
    name: "Furniture Item 10075",
    imageUrl: "/assets/categories/furniture/10075.jpg",
    category: "Furniture",
    description: "Classic furniture suitable for interiors.",
  },
  {
    id: 124,
    name: "Furniture Item 10164",
    imageUrl: "/assets/categories/furniture/10164.jpg",
    category: "Furniture",
    description: "Premium wooden furniture piece.",
  },
  {
    id: 125,
    name: "Furniture Item 10172",
    imageUrl: "/assets/categories/furniture/10172.jpg",
    category: "Furniture",
    description: "Spacious furniture ideal for commercial use.",
  },
  {
    id: 126,
    name: "Furniture Item 10173",
    imageUrl: "/assets/categories/furniture/10173.jpg",
    category: "Furniture",
    description: "Well-designed furniture for modern interiors.",
  },
  {
    id: 127,
    name: "Furniture Item 10174",
    imageUrl: "/assets/categories/furniture/10174.jpg",
    category: "Furniture",
    description: "Strong wooden furniture with classic appeal.",
  },
  {
    id: 128,
    name: "Furniture Item 10176",
    imageUrl: "/assets/categories/furniture/10176.jpg",
    category: "Furniture",
    description: "Traditional furniture crafted with care.",
  },
  {
    id: 129,
    name: "Furniture Item 10177",
    imageUrl: "/assets/categories/furniture/10177.jpg",
    category: "Furniture",
    description: "Elegant furniture suitable for living rooms.",
  },
  {
    id: 130,
    name: "Furniture Item 10184",
    imageUrl: "/assets/categories/furniture/10184.jpg",
    category: "Furniture",
    description: "Premium furniture with solid wooden finish.",
  },
  {
    id: 131,
    name: "Furniture Item 10185",
    imageUrl: "/assets/categories/furniture/10185.jpg",
    category: "Furniture",
    description: "Modern furniture with functional design.",
  },
];

/* =====================================================
   PUJA PRODUCTS (ID: 201–257)
===================================================== */

export const PUJA_PRODUCTS: Product[] = [
  {
    id: 201,
    name: "Pooja Item 10005",
    imageUrl: "/assets/categories/pooja/10005.jpg",
    category: "Puja Items",
    description:
      "Traditional handcrafted brass pooja item suitable for daily rituals.",
  },
  {
    id: 202,
    name: "Pooja Item 10006",
    imageUrl: "/assets/categories/pooja/10006.jpg",
    category: "Puja Items",
    description: "Elegant brass pooja décor with traditional design.",
  },
  {
    id: 205,
    name: "Pooja Item 10043",
    imageUrl: "/assets/categories/pooja/10043.jpg",
    category: "Puja Items",
    description: "Traditional brass craftsmanship for auspicious occasions.",
  },
  {
    id: 206,
    name: "Pooja Item 10053",
    imageUrl: "/assets/categories/pooja/10053.jpg",
    category: "Puja Items",
    description: "Handcrafted brass pooja décor with fine detailing.",
  },
  {
    id: 207,
    name: "Pooja Item 10054",
    imageUrl: "/assets/categories/pooja/10054.jpg",
    category: "Puja Items",
    description: "Traditional kuthu vilakku style brass item.",
  },
  {
    id: 208,
    name: "Pooja Item 10055",
    imageUrl: "/assets/categories/pooja/10055.jpg",
    category: "Puja Items",
    description: "Classic brass diya suitable for festivals.",
  },
  {
    id: 209,
    name: "Pooja Item 10056",
    imageUrl: "/assets/categories/pooja/10056.jpg",
    category: "Puja Items",
    description: "Decorative brass pooja lamp.",
  },
  {
    id: 210,
    name: "Pooja Item 10057",
    imageUrl: "/assets/categories/pooja/10057.jpg",
    category: "Puja Items",
    description: "Traditional temple brass décor.",
  },
  {
    id: 211,
    name: "Pooja Item 10058",
    imageUrl: "/assets/categories/pooja/10058.jpg",
    category: "Puja Items",
    description: "Handcrafted brass pooja accessory.",
  },
  {
    id: 212,
    name: "Pooja Item 10059",
    imageUrl: "/assets/categories/pooja/10059.jpg",
    category: "Puja Items",
    description: "Elegant brass item for spiritual use.",
  },
  {
    id: 213,
    name: "Pooja Item 10060",
    imageUrl: "/assets/categories/pooja/10060.jpg",
    category: "Puja Items",
    description: "Traditional brass décor with antique finish.",
  },
  {
    id: 214,
    name: "Pooja Item 10061",
    imageUrl: "/assets/categories/pooja/10061.jpg",
    category: "Puja Items",
    description: "Compact brass pooja item for daily worship.",
  },
  {
    id: 215,
    name: "Pooja Item 10062",
    imageUrl: "/assets/categories/pooja/10062.jpg",
    category: "Puja Items",
    description: "Fine-finish brass pooja lamp.",
  },
  {
    id: 216,
    name: "Pooja Item 10063",
    imageUrl: "/assets/categories/pooja/10063.jpg",
    category: "Puja Items",
    description: "Traditional brass item with elegant design.",
  },
  {
    id: 217,
    name: "Pooja Item 10064",
    imageUrl: "/assets/categories/pooja/10064.jpg",
    category: "Puja Items",
    description: "Handmade brass pooja décor.",
  },
  {
    id: 218,
    name: "Pooja Item 10065",
    imageUrl: "/assets/categories/pooja/10065.jpg",
    category: "Puja Items",
    description: "Classic brass lamp for auspicious occasions.",
  },
  {
    id: 219,
    name: "Pooja Item 10066",
    imageUrl: "/assets/categories/pooja/10066.jpg",
    category: "Puja Items",
    description: "Temple-inspired brass pooja accessory.",
  },
  {
    id: 220,
    name: "Pooja Item 10089",
    imageUrl: "/assets/categories/pooja/10089.jpg",
    category: "Puja Items",
    description: "Traditional brass pooja item with rich detailing.",
  },

  {
    id: 221,
    name: "Pooja Item 10091",
    imageUrl: "/assets/categories/pooja/10091.jpg",
    category: "Puja Items",
    description: "Handcrafted brass décor for temples.",
  },
  {
    id: 222,
    name: "Pooja Item 10092",
    imageUrl: "/assets/categories/pooja/10092.jpg",
    category: "Puja Items",
    description: "Elegant brass pooja accessory.",
  },
  {
    id: 223,
    name: "Pooja Item 10093",
    imageUrl: "/assets/categories/pooja/10093.jpg",
    category: "Puja Items",
    description: "Traditional brass item for rituals.",
  },
  {
    id: 225,
    name: "Pooja Item 10095",
    imageUrl: "/assets/categories/pooja/10095.jpg",
    category: "Puja Items",
    description: "Antique-style brass pooja décor.",
  },
  {
    id: 226,
    name: "Pooja Item 10099",
    imageUrl: "/assets/categories/pooja/10099.jpg",
    category: "Puja Items",
    description: "Premium handcrafted brass item.",
  },
  {
    id: 227,
    name: "Pooja Item 10100",
    imageUrl: "/assets/categories/pooja/10100.jpg",
    category: "Puja Items",
    description: "Traditional brass pooja décor.",
  },
  {
    id: 228,
    name: "Pooja Item 10102",
    imageUrl: "/assets/categories/pooja/10102.jpg",
    category: "Puja Items",
    description: "Classic brass lamp design.",
  },
  {
    id: 229,
    name: "Pooja Item 10103",
    imageUrl: "/assets/categories/pooja/10103.jpg",
    category: "Puja Items",
    description: "Temple-use brass pooja item.",
  },
  {
    id: 230,
    name: "Pooja Item 10105",
    imageUrl: "/assets/categories/pooja/10105.jpg",
    category: "Puja Items",
    description: "Traditional brass pooja décor.",
  },

  {
    id: 231,
    name: "Pooja Item 10109",
    imageUrl: "/assets/categories/pooja/10109.jpg",
    category: "Puja Items",
    description: "Handcrafted brass pooja item.",
  },
  {
    id: 232,
    name: "Pooja Item 10110",
    imageUrl: "/assets/categories/pooja/10110.jpg",
    category: "Puja Items",
    description: "Large brass vilakku style décor.",
  },
  {
    id: 233,
    name: "Pooja Item 10113",
    imageUrl: "/assets/categories/pooja/10113.jpg",
    category: "Puja Items",
    description: "Classic temple brass pooja lamp.",
  },
  {
    id: 234,
    name: "Pooja Item 10116",
    imageUrl: "/assets/categories/pooja/10116.jpg",
    category: "Puja Items",
    description: "Traditional brass décor with fine finish.",
  },
  {
    id: 235,
    name: "Pooja Item 10118",
    imageUrl: "/assets/categories/pooja/10118.jpg",
    category: "Puja Items",
    description: "Handcrafted brass pooja décor.",
  },
  {
    id: 236,
    name: "Pooja Item 10119",
    imageUrl: "/assets/categories/pooja/10119.jpg",
    category: "Puja Items",
    description: "Elegant brass lamp design.",
  },
  {
    id: 237,
    name: "Pooja Item 10120",
    imageUrl: "/assets/categories/pooja/10120.jpg",
    category: "Puja Items",
    description: "Temple-style brass vilakku.",
  },
  {
    id: 238,
    name: "Pooja Item 10136",
    imageUrl: "/assets/categories/pooja/10136.jpg",
    category: "Puja Items",
    description: "Traditional brass décor.",
  },
  {
    id: 239,
    name: "Pooja Item 10137",
    imageUrl: "/assets/categories/pooja/10137.jpg",
    category: "Puja Items",
    description: "Classic brass pooja lamp.",
  },
  {
    id: 240,
    name: "Pooja Item 10138",
    imageUrl: "/assets/categories/pooja/10138.jpg",
    category: "Puja Items",
    description: "Handcrafted temple décor.",
  },

  {
    id: 241,
    name: "Pooja Item 10139",
    imageUrl: "/assets/categories/pooja/10139.jpg",
    category: "Puja Items",
    description: "Traditional brass pooja item.",
  },
  {
    id: 242,
    name: "Pooja Item 10140",
    imageUrl: "/assets/categories/pooja/10140.jpg",
    category: "Puja Items",
    description: "Elegant brass pooja décor.",
  },
  {
    id: 243,
    name: "Pooja Item 10142",
    imageUrl: "/assets/categories/pooja/10142.jpg",
    category: "Puja Items",
    description: "Temple-style brass lamp.",
  },
  {
    id: 244,
    name: "Pooja Item 10143",
    imageUrl: "/assets/categories/pooja/10143.jpg",
    category: "Puja Items",
    description: "Traditional brass décor for rituals.",
  },
  {
    id: 245,
    name: "Pooja Item 10144",
    imageUrl: "/assets/categories/pooja/10144.jpg",
    category: "Puja Items",
    description: "Classic brass vilakku.",
  },
  {
    id: 246,
    name: "Pooja Item 10145",
    imageUrl: "/assets/categories/pooja/10145.jpg",
    category: "Puja Items",
    description: "Handcrafted brass décor.",
  },
  {
    id: 247,
    name: "Pooja Item 10147",
    imageUrl: "/assets/categories/pooja/10147.jpg",
    category: "Puja Items",
    description: "Traditional brass temple item.",
  },
  {
    id: 248,
    name: "Pooja Item 10148",
    imageUrl: "/assets/categories/pooja/10148.jpg",
    category: "Puja Items",
    description: "Elegant brass pooja lamp.",
  },
  {
    id: 249,
    name: "Pooja Item 10149",
    imageUrl: "/assets/categories/pooja/10149.jpg",
    category: "Puja Items",
    description: "Classic handcrafted brass décor.",
  },
  {
    id: 250,
    name: "Pooja Item 10150",
    imageUrl: "/assets/categories/pooja/10150.jpg",
    category: "Puja Items",
    description: "Traditional brass pooja accessory.",
  },

  {
    id: 251,
    name: "Pooja Item 10151",
    imageUrl: "/assets/categories/pooja/10151.jpg",
    category: "Puja Items",
    description: "Temple-use brass décor.",
  },
  {
    id: 252,
    name: "Pooja Item 10152",
    imageUrl: "/assets/categories/pooja/10152.jpg",
    category: "Puja Items",
    description: "Classic brass pooja item.",
  },
  {
    id: 253,
    name: "Pooja Item 10153",
    imageUrl: "/assets/categories/pooja/10153.jpg",
    category: "Puja Items",
    description: "Traditional handcrafted brass décor.",
  },
  {
    id: 254,
    name: "Pooja Item 10154",
    imageUrl: "/assets/categories/pooja/10154.jpg",
    category: "Puja Items",
    description: "Elegant brass temple lamp.",
  },
  {
    id: 255,
    name: "Pooja Item 10155",
    imageUrl: "/assets/categories/pooja/10155.jpg",
    category: "Puja Items",
    description: "Decorative brass pooja lamp.",
  },
  {
    id: 256,
    name: "Pooja Item 10156",
    imageUrl: "/assets/categories/pooja/10156.jpg",
    category: "Puja Items",
    description: "Compact brass pooja décor.",
  },
  {
    id: 257,
    name: "Pooja Item 10187",
    imageUrl: "/assets/categories/pooja/10187.jpg",
    category: "Puja Items",
    description: "Antique-finish brass pooja item.",
  },
];

/* =====================================================
   MERGED PRODUCTS
===================================================== */

export const PRODUCTS: Product[] = [
  ...STATUE_PRODUCTS,
  ...FURNITURE_PRODUCTS,
  ...PUJA_PRODUCTS,
];

/* =====================================================
   CATEGORIES
===================================================== */

export const CATEGORIES: Category[] = [
  {
    id: 1,
    name: "Bronze Statues",
    imageUrl: "/assets/home/bronze.jpeg",
    productCount: STATUE_PRODUCTS.filter(p => p.category === "Bronze Statues").length,
    description:
      "Exquisite bronze statues handcrafted by master artisans, featuring intricate details of deities and spiritual figures that bring divine presence to your sacred spaces.",
  },
  {
    id: 4,
    name: "Home decor bronze",
    imageUrl: "/assets/categories/statues/10030.jpg",
    productCount: STATUE_PRODUCTS.filter(p => p.category === "Home decor bronze").length,
    description:
      "Beautiful bronze handcrafted artifacts designed to elevate and bring artistic warmth to your home decor.",
  },
  {
    id: 3,
    name: "Puja Items",
    imageUrl: "/assets/categories/pooja/10005.jpg",
    productCount: PUJA_PRODUCTS.length,
    description:
      "Sacred puja essentials crafted with devotion, including lamps, bells, and ritual items that enhance your spiritual practices and create an atmosphere of reverence.",
  },
  {
    id: 2,
    name: "Furniture",
    imageUrl: "/assets/categories/furniture/furniture_hero.png",
    productCount: FURNITURE_PRODUCTS.length,
    description:
      "Premium wooden furniture pieces that blend traditional craftsmanship with contemporary design, each item telling a story of heritage and timeless elegance.",
  },
];

export const Gallery: GALLERY[] = [
  {
    id: 1,
    name: "Bronze Statues",
    imageUrl: "/assets/categories/statues/10096.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 2,
    name: "Furniture",
    imageUrl: "/assets/categories/statues/10106.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 3,
    name: "Puja Items",
    imageUrl: "/assets/categories/statues/10045.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 4,
    name: "Wall Decor",
    imageUrl: "/assets/categories/statues/10069.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 5,
    name: "Wooden Handicrafts",
    imageUrl: "/assets/categories/statues/10090.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 6,
    name: "Puja Items",
    imageUrl: "/assets/categories/statues/10115.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 7,
    name: "Wall Decor",
    imageUrl: "/assets/categories/statues/10117.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 8,
    name: "Wooden Handicrafts",
    imageUrl: "/assets/categories/statues/10121.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 9,
    name: "Wooden Handicrafts",
    imageUrl: "/assets/categories/statues/10141.jpg",
    productCount: PRODUCTS.length,
  },
  {
    id: 10,
    name: "Wooden Handicrafts",
    imageUrl: "/assets/categories/statues/10132.jpg",
    productCount: PRODUCTS.length,
  },
];

export const silverIdolsCategory: Category = {
  id: 1,
  name: "Silver Pooja Lamps",
  imageUrl: "/assets/home/1.png",
  description: "Divine silver idols and multi-tiered lamps handcrafted with devotion",
  productCount: 120,
};

export const floralBloomCategory: Category = {
  id: 2,
  name: "Brass Pooja Lamps",
  imageUrl: "/assets/home/2.png",
  description: "Exquisite traditional brass peacock vilakkus and oil lamps",
  productCount: 85,
};

/* =====================================================
   TESTIMONIALS
===================================================== */

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    quote: "Excellent quality handcrafted products.",
    author: "Rajesh Kumar",
    location: "Kumbakonam",
  },
  {
    id: 2,
    quote: "Beautiful traditional furniture and pooja items.",
    author: "Meena Sundaram",
    location: "Thanjavur",
  },
  {
    id: 3,
    quote: "Authentic bronze statues with amazing craftsmanship.",
    author: "Venkatesh Iyer",
    location: "Trichy",
  },
];
